package com.unispace.lms.enums.plan;

public enum PlanGoalEmploymentType {
  ENTERING_EXITING_EMPLOYMENT,
  APPEARANCE_HYGIENE,
  TASK_COMPLETION_JOB_LEARNING,
  ATTENDANCE_TIMESHEET_PAYCHECKS,
  COWORKER_RELATIONSHIPS,
  JOB_SAFETY,
  POSITIVE_WORKER_BEHAVIORS
}
