package com.unispace.lms.enums.plan;

public enum PlanGoalPersonalManagementType {
  PERSONAL_CARE,
  CLOTHING,
  PLANNING_AND_SCHEDULING,
  CALENDARS_AND_CONTACTS,
  MAILING_AND_POSTAGE,
  SELF_REGULATION,
  SELF_ADVOCACY,
  SELF_AWARENESS,
  LEISURE_SKILLS,
  TECH_SKILLS,
  COMMUNITY_ENGAGEMENT
}
