spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/unispace_lms
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#    show-sql: true

---

spring:
  config:
    activate:
      on-profile: staging
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://unispace-lms-staging.postgres.database.azure.com/unispace_lms_staging
    username: unispace_lms_staging
    password: "NH=M.ueHm#3*n1JeM[0M7P~GZ"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090