spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unispace_lms
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect