package com.unispace.lms.enums;

public enum GoalHomeManagementType {
  ENTERING_EXITING_HOUSING,
  PROBLEM_SOLVING,
  GENERAL_CLEANING_HOUSEKEEPING,
  BATHROOM_KITCHEN_BEDROOM_CLEANING,
  HOME_ORGANIZATION,
  APPLIANCE_USE,
  GENERAL_MAINTENANCE,
  HOME_REPAIRS
}
