package com.unispace.lms.enums;

public enum GoalHealthyRelationshipType {
  CONVERSATION_SKILLS,
  LIVING_WITH_OTHERS,
  GUESTS_AND_ENTERTAINING,
  GROUP_INTERACTION_PARTICIPATION,
  PERSONAL_INTIMATE_RELATIONSHIPS,
  RELATIONSHIP_SAFETY,
  INTERPERSONAL,
  SOCIAL_AWARENESS
}
