package com.unispace.lms.enums;

public enum GoalPersonalManagementType {
  PERSONAL_CARE,
  CLOTHING,
  PLANNING_AND_SCHEDULING,
  CALENDARS_AND_CONTACTS,
  MAILING_AND_POSTAGE,
  SELF_REGULATION,
  SELF_ADVOCACY,
  SELF_AWARENESS,
  LEISURE_SILLS,
  TECH_SKILLS,
  COMMUNITY_ENGAGEMENT
}
