package com.unispace.lms.enums;

public enum StrengthOrConcernType {
  STRENGTH_STUDENT,
  STRENGTH_FAMILY,
  CONCERN_STUDENT,
  CONCERN_FAMILY,
  TEACHER_IDENTIFIED_STRENGTH,
  TEACHER_IDENTIFIED_CONCERN
}
